name: Generate ASCII Artwork

on:
    push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        defaults:
            run:
              shell: bash
              working-directory: ./workflows
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: List the files
              run: |
                pwd
                ls -ltra

            - name: Executing Shell Script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh