name: Generate ASCII Artwork

on:
    push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        defaults:
            run: 
                working-directory: techvmuppa/actions-1/.github/workflows
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v7

            - name: List the files
              run: ls -ltra

            - name: Executing Shell Script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh