name: Exploring variables and secrets

on: 
    push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: techvmuppa
    IMAGE_NAME: github-actions-nginx

jobs:
    docker:
    runs-on: ubuntu-latest
    steps:
        - name: Docker Build
          run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

        - name: Docker Login
          env:
            DOCKER_PASSWORD: S3cureS3crets
          run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

        - name: Docker publish
          run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/IMAGE_NAME:latest


    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:

            - name: Docker Deploy
              run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest


#################################### ENVIRONMENT VARIABLES AT JOB LEVEL #################################
    #     env:
    #         CONTAINER_REGISTRY: docker.io
    #         DOCKER_USERNAME: techvmuppa
    #         IMAGE_NAME: github-actions-nginx

    # runs-on: ubuntu-latest
    # steps:
    #     - name: Docker Build
    #       run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    #     - name: Docker Login
    #       env:
    #         DOCKER_PASSWORD: S3cureS3crets
    #       run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

    #     - name: Docker publish
    #       run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/IMAGE_NAME:latest


    # deploy:
        
    #     env:
    #         CONTAINER_REGISTRY: docker.io
    #         DOCKER_USERNAME: techvmuppa
    #         IMAGE_NAME: github-actions-nginx

    #     needs: docker
    #     runs-on: ubuntu-latest

    #     - name: Docker Deploy
    #       run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest


    ########################### ENVIRONMENT VARIABLE AT STEP LEVEL ###################################

    # steps:
    #     - name: Docker buid
    #       env:
    #         CONTAINER_REGISTRY: docker.io
    #         DOCKER_USERNAME: techvmuppa
    #         IMAGE_NAME: github-actions-nginx
    #       run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    #     - name: Docker login
    #       env:
    #         DOCKER_PASSWORD: S3cretS3ecret
    #         DOCKER_USERNAME: techvmuppa
    #       run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

    #     - name: Docker Publish
    #       env:
    #         DOCKER_REGISTRY: docker.io
    #         DOCKER_USERNAME: techvmuppa
    #         IMAGE_NAME: github-actions-nginx
    #       run: echo docker push $DOCKER_REGISTERY/$DOCKER_USERNAME/$IMAGE_NAME:latest


    # deploy:
    #     needs: docker
    #     runs-on: ubuntu-latest
    # steps:
    #     - name: Docker Deploy
    #       env: 
    #         DOCKER_REGISTRY: docker.io
    #         DOCKER_USERNAME: techvmuppa
    #         IMAGE_NAME: github-actions-nginx

    #       run: echo docer run -d -p 8080:80 $DOCKER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest


###################### WITHOUT VARIABLES ENVIRONEMT ###############################
    # steps:

    #     - name: Docker build
    #       run: docker build -t docker.io/dockerUsername/imageName:latest
    #     - name: Docker login
    #       run: docker login --username=dockerUsername --password=s3curepassword
    #     - name: docker publish
    #       run: docker push docker.io/dockerUsername/imageName:latest
    
    # deploy:
    # needs: docker
    # runs-on: ubuntu-latest
    # steps:
    #     - name: Docker run
    #       run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest
    