name: Workflow Filtering and Activities

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - '!feature/*'  #ignore pushing to anybranch name starts with feature
    pull-request:
        types:
            - opened
            - closed
        paths-ignore:
            - README.md
        branches:
            - main


jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo this workflow/job/step is executed for event type ${{ github.event_name}}
